---
swagger: "2.0"
info:
    title: A cgm bistro menu crawler
    description: A cgm bistro menu crawler
    version: 1.0.0
consumes:
    - application/json
produces:
    - application/json
schemes:
    - http
paths:
    /:
        get:
            tags:
                - api
            responses:
                200:
                    description: list all queued jobs
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/job"
                default:
                    description: generic error response
                    schema:
                        $ref: "#/definitions/error"
        post:
            tags:
                - api
            operationId: addOne
            parameters:
                -   name: body
                    in: body
                    schema:
                        type: string
            responses:
                201:
                    description: Created
                    schema:
                        type: string
                default:
                    description: error
                    schema:
                        $ref: "#/definitions/error"
    /{id}:
        get:
            tags:
                - api
            operationId: getOne
            parameters:
                -   type: string
                    name: id
                    in: path
                    required: true
            responses:
                200:
                    description: Retrieve one job
                    schema:
                        $ref: "#/definitions/job"
                default:
                    description: error
                    schema:
                        $ref: "#/definitions/error"
definitions:
    job:
        type: object
        required:
            - id
        properties:
            id:
                type: string
            dateToParse:
                type: string
            status:
                type: string
            enqueued:
                type: string
            started:
                type: string
            finished:
                type: string
            additional:
                type: array
                items:
                    type: string
    error:
        type: object
        required:
            - message
        properties:
            code:
                type: integer
                format: int64
            message:
                type: string
