
name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/rate-my-bistro/crawler:latest
